version: '3.8'

services:
  php-apache:
    container_name: wishinglist-php
    build: .
    image: wishinglist
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html
      - ./include:/var/www/include
    ports:
      - 80:80
    environment:
      - AZURE_MYSQL_HOST=mysql

  mysql:
    container_name: wishinglist-mysql
    image: docker.io/mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/var/lib/mysql